### ISSUE TITLE
TODO List #1

### ISSUE THREAD

**Issue by Maxqia** [Maxqia/PoreRT#11]
- [x] Mixins for "full" ProtocolSupport compatbibilty
- [x] Auto-Patch to Spigot
- [ ] Document PoreRT a lot better
- [ ] Update to 1.9 Blocks (Sponge just updated)
- [x] Merge reflection to 1.11
- [x] Make master repo 1.11 and add a backport repo for 1.10
- [x] Take a hint from Cauldron : [Material.java](https://github.com/Techcable/Cauldron-Old/blob/master/patches/org/bukkit/Material.java.patch),
- [x] [GameMode.java](https://github.com/Techcable/Cauldron-Old/commit/8beea13e84e6a80b12f506906cb2605106b4b7b9)

**Comment by Maxqia** [comment]
Good Enough
